ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('get_product_name_suggestions/', views.get_product_name_suggestions, name='get_product_name_suggestions'),
    path('<int:product_id>/', views.product_details, name='product_details'),
    path('<int:product_id>/add_review/', views.add_review, name='add_review'),
]

ecommerce/products/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Product(models.Model):
    products_id = models.AutoField(primary_key=True)
    products_name = models.CharField(max_length=100)
    products_price = models.DecimalField(max_digits=10, decimal_places=2)
    products_rating = models.DecimalField(max_digits=3, decimal_places=2, validators=[MinValueValidator(1), MaxValueValidator(5)], null=True, blank=True)
    products_description = models.TextField()
    products_image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.products_name


class Review(models.Model):
    review_id = models.AutoField(primary_key=True)
    review_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_user = models.CharField(max_length=50, null=True, blank=True)
    review_rating = models.DecimalField(max_digits=2, decimal_places=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    review_content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review_product.products_name

ecommerce/products/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from .models import Product, Review
from django.db.models import Avg
from django.http import JsonResponse


def product_list(request):
    query = request.GET.get('search_field', '')
    products = Product.objects.all().order_by('products_id')

    if 'search_field' in request.GET:
        if not query or len(query) < 3:
            messages.error(request, 'Please enter at least 3 characters.')
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            products = products.filter(products_name__icontains=query)

    return render(request, 'products/product_list.html', {'products': products, 'query': query})


def get_product_name_suggestions(request):
    query = request.GET.get('query', '')
    if len(query) >= 3:
        suggestions = Product.objects.filter(products_name__icontains=query).values_list('products_name', flat=True)
        return JsonResponse({'suggestions': list(suggestions)})
    return JsonResponse({'suggestions': []})


def product_details(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'products/product_details.html', {'product': product})


def add_review(request, product_id):
    if request.method == 'POST':
        uname = request.POST.get('uname')
        rating = request.POST.get('rating')
        content = request.POST.get('content')
        product = get_object_or_404(Product, pk=product_id)

        if not uname:
            uname = 'Anonymous'

        if rating and content:
            review = Review(review_product=product, review_user=uname, review_rating=rating, review_content=content)
            review.save()

            avg_rating = Review.objects.filter(review_product=product).aggregate(Avg('review_rating'))['review_rating__avg']
            product.products_rating = avg_rating
            product.save()

            messages.success(request, 'Review added successfully.')
        else:
            messages.error(request, 'Rating and review field required.')

    return redirect('products:product_details', product_id=product_id)

ecommerce/products/templates/products/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}
        <div class="w-full md:w-1/2 lg:w-1/3 px-2 absolute top-16 md:inset-x-1/4 lg:inset-x-1/3">
            <div id="alert" class="alert alert-{{ message.tags }} hidden shadow transition ease-in-out duration-500">
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                        {% if message.tags == 'success' %} 
                            d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" 
                        {% else %} 
                            d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" 
                        {% endif %} 
                    />
                </svg>
                <span>{{ message }}</span>
            </div>
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

ecommerce/products/templates/products/navbar.html
<div class="navbar bg-base-200">
    <div class="flex-1">
        <a href="/products" class="btn btn-ghost normal-case text-xl hover:bg-base-200">Ecommerce Django</a>
    </div>
    <div class="flex-none gap-2">
        <form method="GET" action="{% url 'products:product_list' %}">
            <div class="form-control">
                <div class="input-group">
                    <input id="searchInput" type="search" name="search_field" placeholder="Search by name" class="input input-bordered w-24 md:w-auto" autocomplete="off" />
                    <button class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                        </svg>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<ul id="suggestions" class="mt-0 w-full md:w-[42%] lg:w-[18.5%] bg-white border absolute top-14 md:right-2 lg:right-[350px] z-10 hidden">

</ul>

ecommerce/products/templates/products/product_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load custom_star_tags %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce Django</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.6.1/dist/full.css" rel="stylesheet" type="text/css" />
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-solid-straight/css/uicons-solid-straight.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-regular-straight/css/uicons-regular-straight.css'>
</head>
<body class="max-w-6xl mx-auto">
    {% include './navbar.html' %}
    {% include './messages.html' %}
    <!-- product details -->
    <h1 class="text-4xl font-serif font-medium text-center my-5">Product Details</h1>
    <div class="mt-10 hero bg-base-200">
        <div class="hero-content w-full flex-col md:flex-row gap-10">
            <div class="w-full md:w-1/2 flex justify-center shadow-2xl bg-base-100">
                <figure><img src="{{ product.products_image.url }}" class="h-96" alt="{{ product.products_name }}" /></figure>
            </div>
            <div class="w-full md:w-1/2 text-center lg:text-left">
                <h1 class="text-5xl font-medium">{{ product.products_name }}</h1>
                <p class="py-4">{{ product.products_description | linebreaksbr }}</p>
                <p class="text-orange-600">${{ product.products_price }}</p>
                {% if product.products_rating %}
                    <p class="text-lg">{{ product.products_rating|stars_display|safe }}</p>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- product review -->
    <div class="my-8">
        <div class="px-4 lg:px-0 flex flex-col-reverse md:flex-row gap-8">
            <div class="w-full md:w-1/2">
                <h2 class="text-xl text-center font-medium mb-3">Customer Reviews</h2>
                <div class="space-y-0">
                    {% for review in product.review_set.all %}
                        <div class="border px-4 py-2">
                            <div class="flex justify-between items-center">
                                <p class="text-lg">{{ review.review_rating|stars_display|safe }}</p>
                                <p class="text-sm text-slate-500">{{ review.created_at }}</p>
                            </div>
                            <p class="text-sm text-slate-500 leading-none">by {{ review.review_user }}</p>
                            <p class="mt-3">{{ review.review_content }}</p>
                        </div>
                        {% empty %}
                            <h3 class="text-center font-medium mb-3">No review found.</h3>
                    {% endfor %}
                </div>
            </div>
            <div class="w-full md:w-1/2">
                <h2 class="text-xl text-center font-medium mb-3">Add a Review</h2>
                <form action="{% url 'products:add_review' product.products_id %}" method="POST" class="space-y-1">
                    {% csrf_token %}
                    <label for="uname" class="block">Enter you name:</label>
                    <input type="text" name="uname" placeholder="John Doe" class="input input-bordered w-full" autocomplete="off" />
                    <label for="rating" class="block">Rating (1-5):</label>
                    <input type="number" name="rating" step="0.1" min="1" max="5" placeholder="4.5" class="input input-bordered w-full" autocomplete="off" />
                    <label for="content" class="block">Review:</label>
                    <textarea name="content" rows="3" class="textarea textarea-bordered w-full" placeholder="Add a comment."></textarea>
                    <br>
                    <button class="btn btn-primary w-full">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'js/products/message.js' %}"></script>
    <script src="{% static 'js/products/suggestion.js' %}"></script>
</body>
</html>

ecommerce/products/templates/products/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load custom_star_tags %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce Django</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.6.1/dist/full.css" rel="stylesheet" type="text/css" />
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-solid-straight/css/uicons-solid-straight.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-regular-straight/css/uicons-regular-straight.css'>
</head>
<body class="max-w-6xl mx-auto">
    {% include './navbar.html' %}
    {% include './messages.html' %}
    {% if products %}
        <h1 class="text-4xl font-serif font-medium text-center my-5">All Products</h1>
        <div class="mb-5 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {% for product in products %}
                <div class="card card-compact bg-base-100 shadow-lg border">
                    <figure><img class="w-60 h-60" src="{{ product.products_image.url }}" alt="{{ product.products_name }}" /></figure>
                    <div class="card-body mt-3">
                        <h2 class="card-title">{{ product.products_name }}</h2>
                        <p class="text-orange-600 text-base">${{ product.products_price }}</p>
                        {% if product.products_rating %}
                            <div class="flex items-center gap-1">
                                <div>{{ product.products_rating|stars_display|safe }}</div>
                                <p class="text-lg text-slate-500 ">({{ product.review_set.count }})</p>
                            </div>
                        {% endif %}
                        <div class="card-actions justify-end">
                            <a href="{% url 'products:product_details' product.products_id %}" class="btn btn-primary">Show Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1 class="text-4xl font-serif font-medium text-center my-5">No product found</h1>
    {% endif %}
    <script src="{% static 'js/products/message.js' %}"></script>
    <script src="{% static 'js/products/suggestion.js' %}"></script>
</body>
</html>